### ISSUE TITLE
Using old SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by dnuriel** [GoogleCloudPlatform/cloud-debug-python#1]
python 2.7
Getting "AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'"

"SignedJwtAssertionCredentials was removed from the oath2client python package in the 2.0.0 update. It was no more under oauth2client.client. The behaviour has been moved onto oauth2client.service_account.ServiceAccountCredentials"

**Comment by b-daniels** [comment]
Thanks for pointing this out. When we build our packages for pypi, we're using an older version of oauth2client, so we don't see this issue. I'm working on getting our internal version in sync with the external version (or cherrypicking the right changes) so that we can update the code. Meanwhile, you should be able to fetch the debugger from pypi if you're looking for a simple workaround.

**Comment by b-daniels** [comment]
Update: It appears that p12 files are slowly getting deprecated across a variety of tools, and the oauth2client 3.0 support for p12 files depends on pyOpenSSL. Rather than add a dependency on another component (which may in turn decide to deprecate p12 support at some point), I'm currently testing a fix which changes us over to JSON auth. I believe the long-term benefit is worth any short-term pain here, especially since most people using p12 auth are currently broken anyway.

**Comment by b-daniels** [comment]
Oops. Closed by mistake. I should be able to get the fix out today or Monday.

**Comment by b-daniels** [comment]
This issue has been fixed for a while. Closing.
