### ISSUE TITLE
Support Alpine python images better

### ISSUE THREAD

**Issue by salberin** [GoogleCloudPlatform/cloud-debug-python#10]
I recently spend 2 days attempting to get Google Cloud Debugger to work on a Python 3.6 container where in the end the problem was that the container was using the official python-alpine image. With Alpine Linux being so prevalent in container images, I'd have hoped that the cloud debugger would support these out of the box.

Is this possible, as the current solution I use (based on your example) is a lot more convoluted than just using `pip install google-cloud-debugger`

**Comment by xinghuadou-google** [comment]
Part of the debugger is written in C/C++ and requires being linked against a C stdlib.
The version we upload on PyPI uses glibc as per the PEP 513 standards.
Even if we distribute binaries for Alpine/musl, we couldn't upload to PyPI, and you wouldn't be able to get it with 'pip install' since there isn't an 'alpine' platform tag. https://github.com/pypa/manylinux/issues/37

**Comment by Mizux** [comment]
Actualy pypa now provide the tag `musllinux_1_1` so you **could** update to pypi.org ;)
