### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by nicoleczhu** [GoogleCloudPlatform/cloud-debug-python#22]
Renovate bot upgraded our docker images to `Python:3.9`

`google-python-cloud-debugger==2.15` is only compatible with 3.7/3.8. 

**Is it possible to upgrade compatibility with Python 3.9 as well?**

Setting `google-python-cloud-debugger==2.15` as a requirement yields:
```
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.15 (from -r requirements.txt (line 17)) (from versions: none)
ERROR: No matching distribution found for google-python-cloud-debugger==2.15 (from -r requirements.txt (line 17))
```

**Comment by di** [comment]
I'll add that since the last release, we also have [`manylinux2010`](https://www.python.org/dev/peps/pep-0571/) and [`manylinux2014`](https://www.python.org/dev/peps/pep-0599/), the latter of which supports additional architectures including ARM, which would help resolve https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/12.

**Comment by jturmel** [comment]
Any idea when this will push out? Now that Python 3.9 is GA for App Engine it makes upgrading to 3.9 in production a no-go because we rely on Cloud Debugger.

**Comment by mctavish** [comment]
Support for Python 3.9 has been added in https://github.com/GoogleCloudPlatform/cloud-debug-python/releases/tag/v2.16 and is available at https://pypi.org/project/google-python-cloud-debugger/2.16/

Let me know if you run into any problems!
