### ISSUE TITLE
Cannot Get Cloud Debugger to Work

### ISSUE THREAD

**Issue by nvictor** [GoogleCloudPlatform/cloud-debug-python#37]
Hi,

We have tried setting up Cloud Debugger for our application but kept getting: `The debugger could not find a debug target for the application`. Below are our environment specification:

```
Environment: App Engine Standard
Python version: 3.9
Cloud Debugger API: enabled
```

Here's the entirety of our `app.yaml`:

```yaml
runtime: python39

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
```

And the entirety of our entry point in our `main.py`:

```python
if __name__ == "__main__":
    # NOTE(victor): GCP debugger
    try:
        # NOTE(victor): This client is only available for Linux
        import googleclouddebugger
        googleclouddebugger.enable()
    except ImportError:
        pass
    app.run(host="127.0.0.1", port=os.environ.get("PORT", 8080))
```

We have `google-python-cloud-debugger` in our `requirements.txt`. This was validated by uncommenting the `import` statement. The application restarted and worked fine.

We have scoured the web for an answer for could not find any.

Thanks in advance for your suggestions.

**Comment by mctavish** [comment]
Sorry for the very delayed response here.

The problem here is that the `googleclouddebugger.enable()` call is in the `if __name__ == "__main__":` block.  That code will only be used when running locally.  When running on app engine, gunicorn will serve the app.

Move the enable call outside of that block and it should work.  Also make sure that you send some traffic to the app to wake it up, otherwise it won't show up as being debuggable.

**Comment by nvictor** [comment]
Oh yea! Thank you so much!
